name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '10/**'
      - '10-slim/**'
      - '11/**'
      - '11-slim/**'
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-20.04]

    strategy:
      fail-fast: false
      matrix:
        version: [10, 10-slim, 11, 11-slim]
        include:
          - version: 10
            docker-context: 10/default
            docker-tags: |
              nicoherbigde/debian:10
              nicoherbigde/debian:buster
          - version: 10-slim
            docker-context: 10-slim/default
            docker-tags: |
              nicoherbigde/debian:10-slim
              nicoherbigde/debian:buster-slim
          - version: 11
            docker-context: 11/default
            docker-tags: |
              nicoherbigde/debian:11
              nicoherbigde/debian:bullseye
          - version: 11-slim
            docker-context: 11-slim/default
            docker-tags: |
              nicoherbigde/debian:11-slim
              nicoherbigde/debian:bullseye-slim

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          pull: true
          push: true
          tags: ${{ matrix.docker-tags }}
